-- +goose Up
ALTER TABLE abilities ADD COLUMN grade TEXT NOT NULL DEFAULT '';
ALTER TABLE skills ADD COLUMN grade TEXT NOT NULL DEFAULT '';
ALTER TABLE items ADD COLUMN grade TEXT NOT NULL DEFAULT '';
ALTER TABLE classes ADD COLUMN grade TEXT NOT NULL DEFAULT '';
ALTER TABLE professions ADD COLUMN grade TEXT NOT NULL DEFAULT '';

-- +goose Down
ALTER TABLE abilities DROP COLUMN grade;
ALTER TABLE skills DROP COLUMN grade;
ALTER TABLE items DROP COLUMN grade;
ALTER TABLE classes DROP COLUMN grade;
ALTER TABLE professions DROP COLUMN grade;
